version: "3.9"
services: 
  redis:  
    container_name: redis_container
    image: redis:alpine
    restart: always
    port: 
      - '6379:6379' 
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./docker_volumes/cache:/data
